name: Performance Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Benchmarks
      run: dotnet run --project tests/HeroMessaging.Benchmarks --configuration Release -- --exporters json --artifacts ./BenchmarkDotNet.Artifacts
      timeout-minutes: 30

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          ./BenchmarkDotNet.Artifacts/**/*.json
          ./BenchmarkDotNet.Artifacts/**/*.html

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          let comment = '## Performance Benchmark Results\n\n';
          comment += 'Benchmark execution completed successfully.\n\n';
          comment += 'For detailed performance regression analysis, see the `Cross-Platform Test Matrix` workflow.\n\n';
          comment += '**Artifacts:** Download the benchmark results from the workflow artifacts.';

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });