name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['6.0.x', '8.0.x', '10.0.x']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test tests/HeroMessaging.Tests/ --no-build --configuration Release --logger trx --collect:"XPlat Code Coverage" --settings coverlet.runsettings --filter "Category=Unit" --verbosity normal
      timeout-minutes: 2

    - name: Run Integration Tests
      run: dotnet test tests/HeroMessaging.Tests/ --no-build --configuration Release --logger trx --collect:"XPlat Code Coverage" --settings coverlet.runsettings --filter "Category=Integration" --verbosity normal
      timeout-minutes: 5

    - name: Run Contract Tests
      run: dotnet test tests/HeroMessaging.Contract.Tests/ --no-build --configuration Release --logger trx --collect:"XPlat Code Coverage" --settings coverlet.runsettings --filter "Category=Contract" --verbosity normal
      timeout-minutes: 3

    - name: Upload test results
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.dotnet-version }}
        path: |
          **/*.trx
          **/TestResults/**/*.xml

    - name: Upload coverage reports
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: coverage-${{ matrix.os }}-${{ matrix.dotnet-version }}
        path: |
          **/TestResults/**/coverage.cobertura.xml