// Copyright (c) HeroMessaging Contributors. All rights reserved.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace HeroMessaging.SourceGenerators;

/// <summary>
/// Generates idempotency key generators based on message properties.
/// </summary>
[Generator]
public class IdempotencyKeyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register attribute source
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("GenerateIdempotencyKeyAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // Find types with [GenerateIdempotencyKey] attribute
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateNode(node),
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static typeInfo => typeInfo.Type is not null);

        // Generate key generators
        context.RegisterSourceOutput(candidates, static (spc, typeInfo) =>
        {
            if (typeInfo.Type is null) return;

            var source = GenerateKeyGenerator(typeInfo.Type, typeInfo.PropertyNames);
            spc.AddSource($"{typeInfo.Type.Name}IdempotencyKeyGenerator.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static bool IsCandidateNode(SyntaxNode node)
    {
        return node is TypeDeclarationSyntax typeDecl &&
               typeDecl.AttributeLists.Count > 0;
    }

    private static (INamedTypeSymbol? Type, string[] PropertyNames) GetSemanticTarget(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;

        if (symbol is null) return (null, Array.Empty<string>());

        // Check for [GenerateIdempotencyKey] attribute
        var attribute = symbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name == "GenerateIdempotencyKeyAttribute" ||
                                   attr.AttributeClass?.Name == "GenerateIdempotencyKey");

        if (attribute is null) return (null, Array.Empty<string>());

        // Extract property names from attribute
        var propertyNames = attribute.ConstructorArguments
            .SelectMany(arg => arg.Values)
            .Select(val => val.Value?.ToString() ?? string.Empty)
            .Where(name => !string.IsNullOrEmpty(name))
            .ToArray();

        return (symbol, propertyNames);
    }

    private static string GenerateKeyGenerator(INamedTypeSymbol type, string[] propertyNames)
    {
        var namespaceName = type.ContainingNamespace.ToDisplayString();
        var typeName = type.Name;
        var generatorName = $"{typeName}IdempotencyKeyGenerator";

        // Validate properties exist
        var properties = new List<IPropertySymbol>();
        foreach (var propName in propertyNames)
        {
            var prop = type.GetMembers()
                .OfType<IPropertySymbol>()
                .FirstOrDefault(p => p.Name == propName);

            if (prop is not null)
            {
                properties.Add(prop);
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using HeroMessaging.Abstractions.Idempotency;");
        sb.AppendLine("using HeroMessaging.Abstractions.Transport;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Auto-generated idempotency key generator for {typeName}.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {generatorName} : IIdempotencyKeyGenerator");
        sb.AppendLine("{");

        // GenerateKey method
        sb.AppendLine("    public string GenerateKey(MessageContext context)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (context.Message is not {typeName} message)");
        sb.AppendLine("        {");
        sb.AppendLine($"            throw new InvalidOperationException($\"Expected message of type {typeName}, got {{context.Message.GetType().Name}}\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var sb = new StringBuilder();");
        sb.AppendLine($"        sb.Append(\"idempotency:{typeName}\");");

        foreach (var prop in properties)
        {
            sb.AppendLine($"        sb.Append(':');");
            sb.AppendLine($"        sb.Append(message.{prop.Name});");
        }

        sb.AppendLine();
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private const string AttributeSource = @"// <auto-generated/>
namespace HeroMessaging.SourceGeneration
{
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    internal sealed class GenerateIdempotencyKeyAttribute : System.Attribute
    {
        public string[] PropertyNames { get; }

        public GenerateIdempotencyKeyAttribute(params string[] propertyNames)
        {
            PropertyNames = propertyNames ?? System.Array.Empty<string>();
        }
    }
}";
}
